### ISSUE TITLE
Not able to join discord

### ISSUE THREAD

**Issue by VeoMorphine** [Jerry1211/RadarProject#1]
Is something going on with discord? I posted up an hour ago regarding it and got a reply saying that I might be banned. Came back to post this:
![image](https://user-images.githubusercontent.com/37481618/37559162-8b4e9f62-29f7-11e8-9395-68b79c7fb5b8.png)
To show that I can't join even with a new account. Any help? I was trying to work with someone to get a wireshark capture for the xbox so I could attempt to implement some type of xbox support. I can't get in contact with them now.

**Comment by Jerry1211** [comment]
put it in your browswer not in discord

**Comment by VeoMorphine** [comment]
I also tried in my browser. It did the same thing.

**Comment by L-KE** [comment]
Bro, that's not an instant invite, its a third party website. You have to go to that link.

**Comment by VeoMorphine** [comment]
https://i.imgur.com/1enGAEu.gifv

Bro, That's what I did. See?

**Comment by SamuelNZ** [comment]
The link works, You're probably banned for whatever reason.
