### ISSUE TITLE
nodejs version.

### ISSUE THREAD

**Issue by txchen** [Jerry1211/RadarProject#10]
I have just published my nodejs repo. Check it out: https://github.com/txchen/scichicken

However please don't ask questions, since I am not playing the game anymore. I believe the code is not hard to understand, so please enjoy DIY hacking.

**Comment by L-KE** [comment]
bruh, this looks fucking sick. well-commented code made by someone who actually knows what they're doing. good shit.

**Comment by SamuelNZ** [comment]
Hahah you think the public release is the best version. Fucking retard.
