### ISSUE TITLE
severe network lag 

### ISSUE THREAD

**Issue by toolsofpwnage** [Jerry1211/RadarProject#16]
Help, I keep getting "network lag detected" randomly throughout the match. I suspect it might have something to do with the vpn or middle pc. Does the gaming pc must go through a vpn, is it safe enough to run without it?

**Comment by mcalis** [comment]
I started getting "network lag detected" from yesterday. I don't know. Till now it was working perfect.
Maybe it has something to do with blueballs's servers.

This radar is such a joy to have. Great job jerry and others !!
