### ISSUE TITLE
why dont have level 3 

### ISSUE THREAD

**Issue by MrRemix1** [Jerry1211/RadarProject#18]
why dont have level 3

**Comment by abazad** [comment]
You can't filter level 3 gear **(always enabled)**

you should read Readme.

**Comment by MrRemix1** [comment]
but the Radar dont have level 3 gear

**Comment by EiTeR94** [comment]
yep, can't see level 3 gear now..

**Comment by KlerrUC** [comment]
just wait, the devs are workin on that...

**Comment by Kreo69** [comment]
Just comment with /* or // this section in GLMap.kt, 

```
         level3Filter = if (filterLvl3 != 1) {
             arrayListOf("")
         } else {
             arrayListOf("Bag3", "Armor3", "Helmet3")
         }
```
recompile and after that you can see Lvl3 items

**Comment by EiTeR94** [comment]
that's work thanks, have you some thing to fix invisible enemies ?
