### ISSUE TITLE
good luck

### ISSUE THREAD

**Issue by XKReSycj** [Jerry1211/RadarProject#34]
This project is now being sold by the chinese for $5 , sales is growing exponentially. 
The packet will be encrypted as soon as possible , and for any vm, ban wave is coming.

ref: http://www.92jh.cn/dz-3590-1-1.html
http://www.xdowns.com/app/281119.html

**Comment by MadCabalo** [comment]
This will only speed up the encryption they eventually will add.
Chinese...

**Comment by xiaoxin022** [comment]
Turning off the radar's virtual machine mode, the transmission will slow down because not all people have 2nd PC...

**Comment by SamuelNZ** [comment]
You realize we give it away for free right? Cool, Thanks.
