### ISSUE TITLE
discord is down.

### ISSUE THREAD

**Issue by b000sh** [Jerry1211/RadarProject#36]
Not sure what's going on with it.

**Comment by Cyphershoot** [comment]
Same here, my discord project radar is closed, kicked or closed maybe

**Comment by abazad** [comment]
maybe you are just banned.

**Comment by Scarjit** [comment]
Discord is up and running as we speak.


![Discord](https://i.imgur.com/ka5yJZf.png "Discord")

**Comment by SamuelNZ** [comment]
You're probably banned

**Comment by Cyphershoot** [comment]
Banned because I spoken before 1 hour :(

**Comment by SamuelNZ** [comment]
You literally get messaged the rules by a bot stop talking shit.
