### ISSUE TITLE
Discord Got Taken Down?

### ISSUE THREAD

**Issue by Jerry1211** [Jerry1211/RadarProject#38]
So my Discord acc is Locked and the Instant invite doesnt work anymore, no email from discord but i think Bluehole Took us down boys

https://i.imgur.com/S4skp5V.png

**Comment by Scarjit** [comment]
RIP. So what now ?
New discord ?
Forum ?
Teamspeak ?

**Comment by lllteolll** [comment]
omg ... i was like wtf is going on where is the server -.- fk you bluehole

**Comment by lllteolll** [comment]
New discord i guess then...

**Comment by Scarjit** [comment]
Well, it will be taken down again.

**Comment by Scarjit** [comment]
I could setup a forum on my webserver, but that would take some time (Hours) and my teamspeak server only fits 32 ppl

**Comment by Jerry1211** [comment]
well rip lmao

**Comment by lllteolll** [comment]
https://imgur.com/EJ5lDUj

**Comment by Jerry1211** [comment]
If you have Telegram catch me in here -> https://t.me/ProjectRadar

**Comment by lllteolll** [comment]
http://jerry1211.freeforums.net/

**Comment by lllteolll** [comment]
how about this?

**Comment by Scarjit** [comment]
https://i.imgur.com/JszT8Ps.png
would be nice to write tho @Jerry1211

**Comment by PostBaloney** [comment]
oof, blueballs...

**Comment by Kitgoba** [comment]
FeelsBadMan, new discord yolo,

**Comment by lllteolll** [comment]
Scarjit said they will take it down again... but i have an idea
we can just limit the users....

**Comment by lllteolll** [comment]
like make an application for trusted ones

**Comment by PostBaloney** [comment]
@lllteolll I agree.

**Comment by Scarjit** [comment]
That goes against the point of a public cheat

**Comment by lllteolll** [comment]
i know but i assume that its someone of the people....

**Comment by lllteolll** [comment]
i mean there was a spy or something

**Comment by Scarjit** [comment]
Of course it is, but it could be nearly everybody.

**Comment by lllteolll** [comment]
yeah...

**Comment by lllteolll** [comment]
so tons of discord or find another app to work on...

**Comment by Scarjit** [comment]
yes, like IRC,some forum, ...

**Comment by Scarjit** [comment]
mattermost ?

**Comment by lllteolll** [comment]
we can use this one http://jerry1211.freeforums.net/

**Comment by Jerry1211** [comment]
some oone purchase a VMRadar.net domain :)

**Comment by Scarjit** [comment]
ok

**Comment by lllteolll** [comment]
cool 💃

**Comment by Jerry1211** [comment]
its time for the community to pay it forward, help the devs out ahah

**Comment by RaidernW** [comment]
Why dont you set up a teamspeak and accept donations to make the payment monthly I have no doubt you guys  could get the amount in donations how many members were you guys avg?

**Comment by lllteolll** [comment]
can u ask him if he needs me to help with the payment?

**Comment by PostBaloney** [comment]
300+ members

**Comment by Scarjit** [comment]
@Jerry1211 ez
https://i.imgur.com/qa7IHls.png

**Comment by RaidernW** [comment]
rip lol

**Comment by Scarjit** [comment]
already have a decent webserver, so why not

**Comment by Scarjit** [comment]
@Jerry1211 do you got teamspeak so we can talk about the website ?

**Comment by Scarjit** [comment]
https://i.imgur.com/NoylwLK.png

hehe

**Comment by Jerry1211** [comment]
yeah email me the link @ jerry1211jerry1211@gmail.com

**Comment by ReddeR1337** [comment]
@Jerry1211 and me to telegram please :D

**Comment by hkuuki** [comment]
just let me know if u guys need servers or whatever, look likes @Scarjit already got domain

**Comment by Scarjit** [comment]
got a server

**Comment by lllteolll** [comment]
Scarjit if u need any help with anything let me know

**Comment by lllteolll** [comment]
i'm a web designer

**Comment by Scarjit** [comment]
ok

**Comment by hkuuki** [comment]
@Jerry1211 try to create a telegram group but not a channel, so we can talk together to go through this   shit.

**Comment by ReddeR1337** [comment]
payment cheat fo pubg = dont get banned or detected
free cheat fo pubg =ALLAHU AKBAR, kill discord

**Comment by ShakeJunk** [comment]
Looked at Discord and thought im blind but damn actually sad that it got taken down :D

**Comment by caoliu1118** [comment]
:(

**Comment by Scarjit** [comment]
Forum is up @ https://vmradar.net

**Comment by Xero852** [comment]
@Scarjit lots of people signing up right now? Validation email isn't coming through for a few minutes. Usually instant with most web servers/forums I run.

**Comment by Scarjit** [comment]
@Xero852 yes, currently getting spammed a bit, but you should be unlocked manually now ;)

**Comment by Xero852** [comment]
@Scarjit cheers!

**Comment by wuwujia** [comment]
a telegram group would be fine too.

**Comment by Th3C0D3R** [comment]
lol did he crashed the website??? xD

**Comment by Wruczek** [comment]
I second that, Telegram group for messages and Telegram channel for announcements would be the best imo

**Comment by Jerry1211** [comment]
Website -> https://vmradar.net
