### ISSUE TITLE
Item_Weapon_FlareGun

### ISSUE THREAD

**Issue by lonelytb** [Jerry1211/RadarProject#39]
Added in Event Mode.
Ammo name is Item_Ammo_Flare.

PNGs:
![Gun](http://ww1.sinaimg.cn/large/006NGikrgy1fplima1445j306o06ojs4.jpg)
![Ammo](http://ww1.sinaimg.cn/large/006NGikrgy1fplima6isyj306o06oq3z.jpg)

And spawn spot (in custom game, not tested in live server, from WackyJack101's video), draw them on map?
![Map](http://ww1.sinaimg.cn/large/006NGikrgy1fplizbnqyhj30k00jw1kx.jpg)

**Comment by Jerry1211** [comment]
get a pcap and pm me on VMRadar.net

**Comment by SamuelNZ** [comment]
Implemented.
