### ISSUE TITLE
Black map!

### ISSUE THREAD

**Issue by liquidvn** [Jerry1211/RadarProject#6]
![untitled](https://user-images.githubusercontent.com/37448780/37528068-35893934-2966-11e8-8999-cfa927a812d0.png)

The radar work properly but the background map is just a black screen!

**Comment by xXSkrill1337** [comment]
Me to

**Comment by MioYvo** [comment]
same error

**Comment by MadCabalo** [comment]
Only on Erangel though, as Miramar is properly displayed. I will look into the code and try to find the cause.

**Comment by xXSkrill1337** [comment]
Me to im trying ....

**Comment by MadCabalo** [comment]
Can you confirm that Miramar displays correctly?

**Comment by xXSkrill1337** [comment]
Im cheking this

**Comment by xXSkrill1337** [comment]
i need to rebuild this xD

**Comment by xXSkrill1337** [comment]
Miramar is broke to ...

**Comment by MadCabalo** [comment]
Solved upon latest commits.

**Comment by MioYvo** [comment]
Tested commits [dont break on my baby](https://github.com/Jerry1211/RadarProject/commit/ea1f97423d90cc2b4d26bc8f2b52f872112b075d) fix this bugs, thx
